version: '2.1'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=corpora
      - POSTGRES_PASSWORD=test_pw
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./.devenv/postgres:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,secretsmanager
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./.devenv/localstack:/tmp/localstack
  frontend:
    image: corpora-frontend
    build: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8000:8000"
    command: ["./container_init.sh"]
    volumes:
      - ./frontend:/corpora-frontend
      - /corpora-frontend/node_modules/
  backend:
    image: corpora-backend
    build: backend
    restart: always
    depends_on:
      - localstack
      - database
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - CORPORA_LOCAL_DEV=true
      - AWS_ACCESS_KEY_ID=dev_access_key_id
      - AWS_SECRET_ACCESS_KEY=dev_secret_access_key
      - BOTO_ENDPOINT_URL=http://localstack:4566
      - DEPLOYMENT_STAGE=dev
    command: ["python3", "run_local_server.py", "--host", "0.0.0.0"]
    volumes:
      - ./backend/chalice/api_server/app.py:/chalice/app.py
      - ./backend/chalice/api_server/run_local_server.py:/chalice/run_local_server.py
      - ./backend/corpora:/chalice/chalicelib/corpora
      - ./backend/config/corpora-api.yml:/chalice/chalicelib/config/corpora-api.yml
